# Generated by Django 4.2.5 on 2025-12-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
                ("release_date", models.DateField(db_index=True)),
                (
                    "evaluation",
                    models.CharField(
                        choices=[
                            ("G", "Tout public"),
                            ("PG", "Accord parental souhaitable"),
                            ("PG-13", "Accord parental recommandé"),
                            ("R", "Interdit aux moins de 17 ans"),
                            ("NC-17", "Interdit aux moins de 18 ans"),
                        ],
                        default="G",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Brouillon"), ("published", "Publié"), ("archived", "Archivé")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("tmdb_id", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("ADMIN", "Administration"), ("TMDB", "Import TMDb")], default="ADMIN", max_length=10
                    ),
                ),
                ("poster", models.ImageField(blank=True, null=True, upload_to="film_posters/")),
                ("average_rating", models.FloatField(db_index=True, default=0.0)),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="FilmReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rating", models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ("comment", models.TextField(blank=True)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="films.film"
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis sur film",
                "verbose_name_plural": "Avis sur films",
            },
        ),
    ]
