# Generated by Django 4.2.5 on 2025-12-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spectators", "0001_initial"),
        ("authors", "0001_initial"),
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="film_reviews", to="spectators.spectator"
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="films", to="authors.author"
            ),
        ),
        migrations.AddIndex(
            model_name="filmreview",
            index=models.Index(fields=["film", "-created_at"], name="review_film_date_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="filmreview",
            unique_together={("film", "user")},
        ),
        migrations.AddIndex(
            model_name="film",
            index=models.Index(fields=["status", "release_date"], name="film_status_date_idx"),
        ),
        migrations.AddIndex(
            model_name="film",
            index=models.Index(fields=["author", "status"], name="film_author_status_idx"),
        ),
        migrations.AddIndex(
            model_name="film",
            index=models.Index(fields=["author", "release_date"], name="film_author_release_idx"),
        ),
    ]
