# Generated by Django 4.2.5 on 2025-12-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0003_initial"),
        ("films", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="film",
            name="film_author_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="film",
            name="film_author_release_idx",
        ),
        migrations.RemoveField(
            model_name="film",
            name="author",
        ),
        migrations.AddField(
            model_name="film",
            name="authors",
            field=models.ManyToManyField(related_name="films", to="authors.author"),
        ),
    ]
