# Generated by Django 4.2.5 on 2025-12-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spectator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "favorite_genre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("action", "Action"),
                            ("comedy", "Comédie"),
                            ("drama", "Drame"),
                            ("horror", "Horreur"),
                            ("scifi", "Science-fiction"),
                            ("romance", "Romance"),
                            ("thriller", "Thriller"),
                            ("animation", "Animation"),
                            ("documentary", "Documentaire"),
                            ("fantasy", "Fantastique"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Genre préféré",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars/")),
                ("favorite_films", models.ManyToManyField(blank=True, related_name="favorited_by", to="films.film")),
            ],
            options={
                "verbose_name": "Spectateur",
                "verbose_name_plural": "Spectateurs",
                "ordering": ["-created_at"],
            },
        ),
    ]
