# Generated by Django 4.2.5 on 2025-12-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("tmdb_id", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("ADMIN", "Administration"), ("TMDB", "Import TMDb")], default="ADMIN", max_length=10
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="author_photos/")),
            ],
            options={
                "verbose_name": "Auteur",
                "verbose_name_plural": "Auteurs",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="AuthorReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rating", models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ("comment", models.TextField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="authors.author"
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis sur auteur",
                "verbose_name_plural": "Avis sur auteurs",
            },
        ),
    ]
