# Generated by Django 4.2.5 on 2025-12-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spectators", "0001_initial"),
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="author_reviews", to="spectators.spectator"
            ),
        ),
    ]
