# Generated by Django 4.2.5 on 2025-12-12 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="author_profile", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="authorreview",
            index=models.Index(fields=["author", "-created_at"], name="author_review_date_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="authorreview",
            unique_together={("author", "user")},
        ),
    ]
